//! User-scoped service and hook installation. No agent trust state is ever written.
use crate::daemon::{self, files::Paths, ipc};
use crate::guardian::recovery;
use crate::platform::{NativePlatform, Platform};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use std::fs::{self, File, OpenOptions};
use std::io::{self, Write};
use std::os::unix::fs::OpenOptionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

const MARKER: &str = " # ballast-managed-hook";
const SERVICE_MARKER: &str = "Generated by Ballast";
const EVENTS: [(&str, &str); 6] = [
    ("PreToolUse", "pre_tool_use"),
    ("PostToolUse", "post_tool_use"),
    ("SessionStart", "session_start"),
    ("UserPromptSubmit", "user_prompt_submit"),
    ("Stop", "stop"),
    ("SessionEnd", "session_end"),
];

pub struct Installation {
    pub home: PathBuf,
    pub paths: Paths,
    pub binary: PathBuf,
    pub claude_dir: PathBuf,
    pub codex_dir: PathBuf,
    pub service_dir: PathBuf,
    pub service_label: String,
}

impl Installation {
    pub fn from_env() -> io::Result<Self> {
        let home = env_path("HOME", None)?;
        let service_default = if cfg!(target_os = "macos") {
            home.join("Library/LaunchAgents")
        } else {
            env_path("XDG_CONFIG_HOME", Some(home.join(".config")))?.join("systemd/user")
        };
        let result = Self {
            paths: Paths {
                base: env_path("BALLAST_HOME", Some(home.join(".ballast")))?,
            },
            binary: std::env::current_exe()?,
            claude_dir: env_path("CLAUDE_CONFIG_DIR", Some(home.join(".claude")))?,
            codex_dir: env_path("CODEX_HOME", Some(home.join(".codex")))?,
            service_dir: env_path("BALLAST_SERVICE_DIR", Some(service_default))?,
            service_label: std::env::var("BALLAST_SERVICE_LABEL")
                .unwrap_or_else(|_| "dev.ballast.daemon".into()),
            home,
        };
        result.validate()?;
        Ok(result)
    }

    fn validate(&self) -> io::Result<()> {
        for path in [
            &self.home,
            &self.paths.base,
            &self.binary,
            &self.claude_dir,
            &self.codex_dir,
            &self.service_dir,
        ] {
            if !path.is_absolute()
                || path
                    .to_str()
                    .is_none_or(|s| s.chars().any(char::is_control))
            {
                return Err(io::Error::other(
                    "installation paths must be absolute UTF-8 paths without control characters",
                ));
            }
        }
        let socket_limit = if cfg!(target_os = "macos") { 104 } else { 108 };
        if self.paths.socket().as_os_str().len() >= socket_limit {
            return Err(io::Error::other(format!(
                "Ballast socket path must be shorter than {socket_limit} bytes; choose a shorter BALLAST_HOME"
            )));
        }
        if self.service_label.is_empty()
            || self.service_label.starts_with('-')
            || !self
                .service_label
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || b"._-".contains(&b))
        {
            return Err(io::Error::other(
                "BALLAST_SERVICE_LABEL must contain only letters, digits, dots, underscores and hyphens",
            ));
        }
        Ok(())
    }

    fn config_files(&self) -> [(PathBuf, &str); 2] {
        [
            (self.claude_dir.join("settings.json"), "claude"),
            (self.codex_dir.join("hooks.json"), "codex"),
        ]
    }

    fn hook_group(&self, event: &str, agent: &str) -> Value {
        let command = format!(
            "env BALLAST_HOME={} {} hook {agent}{MARKER}",
            shell_quote(&self.paths.base),
            shell_quote(&self.binary)
        );
        let mut hook = json!({"type": "command", "command": command, "timeout": if event == "PreToolUse" {600} else {1}});
        if event == "PreToolUse" {
            hook["statusMessage"] = json!("Ballast: waiting for memory headroom");
        }
        let mut group = json!({"hooks": [hook]});
        if event == "PreToolUse" || event == "PostToolUse" {
            group["matcher"] = json!(if agent == "claude" && event == "PreToolUse" {
                "Bash|Monitor"
            } else {
                "Bash"
            });
        }
        group
    }

    fn edits(&self, installing: bool) -> io::Result<Vec<ConfigEdit>> {
        self.config_files()
            .into_iter()
            .map(|(path, agent)| {
                let mut edit = ConfigEdit::read(path)?;
                let before = edit.value.clone();
                let positions = EVENTS.map(|(event, _)| {
                    edit.value["hooks"][event].as_array().and_then(|groups| {
                        groups
                            .iter()
                            .position(|g| g["hooks"].as_array().unwrap().iter().any(owned))
                    })
                });
                remove_owned(&mut edit.value);
                if installing {
                    let hooks = edit
                        .value
                        .as_object_mut()
                        .unwrap()
                        .entry("hooks")
                        .or_insert_with(|| json!({}))
                        .as_object_mut()
                        .unwrap();
                    for ((event, _), position) in EVENTS.into_iter().zip(positions) {
                        let groups = hooks
                            .entry(event)
                            .or_insert_with(|| json!([]))
                            .as_array_mut()
                            .unwrap();
                        // Codex trust keys include group indices; keep the installed slot on upgrades.
                        groups.insert(
                            position.unwrap_or(groups.len()).min(groups.len()),
                            self.hook_group(event, agent),
                        );
                    }
                }
                edit.changed = edit.value != before;
                Ok(edit)
            })
            .collect()
    }

    pub fn install(&self) -> io::Result<()> {
        self.validate()?;
        let edits = self.edits(true)?; // Validate both configs before touching either or the service.
        let service = self.service_file();
        self.check_service_owner(true)?;
        self.paths.prepare()?;
        for edit in edits {
            edit.save()?;
        }
        atomic_write(&service, self.service_text().as_bytes())?;
        self.start_service()?;
        let deadline = Instant::now() + Duration::from_secs(10);
        while !self.reachable() {
            if Instant::now() >= deadline {
                return Err(io::Error::other(
                    "service installed but daemon unreachable; run `ballast doctor` and inspect the user service log",
                ));
            }
            std::thread::sleep(Duration::from_millis(100));
        }
        println!(
            "Ballast installed and running. Open Codex, run /hooks, and approve the Ballast hooks once (again after a hook path changes)."
        );
        Ok(())
    }

    pub fn uninstall(&self, purge: bool) -> io::Result<()> {
        self.validate()?;
        let edits = self.edits(false)?;
        self.check_service_owner(false)?;
        daemon::resume_command(&self.paths, None)?;
        self.stop_service()?;
        // A daemon may freeze again between the first resume and service shutdown.
        // Recover under the directory lock before removing hooks or recovery evidence.
        daemon::resume_command(&self.paths, None)?;
        let _lock = ipc::lock(&self.paths)?;
        if recovery::needs_recovery(&self.paths) {
            return Err(io::Error::other(
                "frozen work remains; run `ballast resume --all` before uninstalling",
            ));
        }
        for edit in edits {
            edit.save()?;
        }
        remove_if_exists(&self.service_file())?;
        #[cfg(target_os = "linux")]
        self.service_command(&["daemon-reload"])?;
        if purge {
            fs::remove_dir_all(&self.paths.base)?;
        }
        println!(
            "Ballast uninstalled; frozen work resumed.{}",
            if purge {
                " Data removed."
            } else {
                " Data retained; use --purge to remove it."
            }
        );
        Ok(())
    }

    fn reachable(&self) -> bool {
        ipc::Client::connect(&self.paths, Duration::from_millis(500))
            .and_then(|mut c| c.request(ipc::Method::Status))
            .is_ok_and(|r| matches!(r.reply, ipc::Reply::Status { .. }))
    }

    pub fn service_file(&self) -> PathBuf {
        self.service_dir.join(format!(
            "{}.{}",
            self.service_label,
            if cfg!(target_os = "macos") {
                "plist"
            } else {
                "service"
            }
        ))
    }

    fn check_service_owner(&self, installing: bool) -> io::Result<()> {
        if let Some(bytes) = read_regular(&self.service_file())? {
            if !String::from_utf8_lossy(&bytes).contains(SERVICE_MARKER) {
                return Err(io::Error::other(
                    "service path contains a non-Ballast service; choose a different BALLAST_SERVICE_LABEL",
                ));
            }
        } else if installing && self.service_running() {
            return Err(io::Error::other(
                "service label is already loaded without a Ballast service file; choose a different BALLAST_SERVICE_LABEL",
            ));
        }
        Ok(())
    }

    fn service_text(&self) -> String {
        #[cfg(target_os = "macos")]
        {
            format!(
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- {SERVICE_MARKER} -->\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\"><dict>\n<key>Label</key><string>{}</string>\n<key>ProgramArguments</key><array><string>{}</string><string>daemon</string></array>\n<key>EnvironmentVariables</key><dict><key>HOME</key><string>{}</string><key>BALLAST_HOME</key><string>{}</string></dict>\n<key>RunAtLoad</key><true/><key>KeepAlive</key><true/>\n</dict></plist>\n",
                xml(&self.service_label),
                xml(self.binary.to_str().unwrap()),
                xml(self.home.to_str().unwrap()),
                xml(self.paths.base.to_str().unwrap())
            )
        }
        #[cfg(target_os = "linux")]
        {
            format!(
                "# {SERVICE_MARKER}\n[Unit]\nDescription=Ballast memory guardian\nStartLimitIntervalSec=0\n\n[Service]\nExecStart=/usr/bin/env -- {} daemon\nEnvironment={} {}\nRestart=always\nRestartSec=1\nRestartSteps=10\nRestartMaxDelaySec=30\n\n[Install]\nWantedBy=default.target\n",
                systemd_quote(self.binary.to_str().unwrap()).replace('$', "$$"),
                systemd_quote(&format!("HOME={}", self.home.display())),
                systemd_quote(&format!("BALLAST_HOME={}", self.paths.base.display()))
            )
        }
    }

    fn service_command(&self, args: &[&str]) -> io::Result<()> {
        let output = service_command().args(args).output()?;
        if !output.status.success() {
            return Err(io::Error::other(format!(
                "user service command failed ({}); run `ballast doctor` and check your user service manager",
                output.status
            )));
        }
        Ok(())
    }

    fn service_running(&self) -> bool {
        #[cfg(target_os = "macos")]
        let args = vec!["print".to_string(), self.service_target()];
        #[cfg(target_os = "linux")]
        let args = vec![
            "is-active".to_string(),
            "--quiet".into(),
            format!("{}.service", self.service_label),
        ];
        service_command()
            .args(args)
            .output()
            .is_ok_and(|o| o.status.success())
    }

    #[cfg(target_os = "macos")]
    fn service_target(&self) -> String {
        format!("gui/{}/{}", unsafe { libc::geteuid() }, self.service_label)
    }

    fn start_service(&self) -> io::Result<()> {
        #[cfg(target_os = "macos")]
        {
            if self.service_running() {
                self.stop_service()?;
            }
            let domain = format!("gui/{}", unsafe { libc::geteuid() });
            self.service_command(&["enable", &self.service_target()])?;
            self.service_command(&["bootstrap", &domain, self.service_file().to_str().unwrap()])
        }
        #[cfg(target_os = "linux")]
        {
            self.service_command(&["daemon-reload"])?;
            self.service_command(&["enable", self.service_file().to_str().unwrap()])?;
            self.service_command(&["restart", &format!("{}.service", self.service_label)])
        }
    }

    fn stop_service(&self) -> io::Result<()> {
        #[cfg(target_os = "macos")]
        if self.service_running() {
            self.service_command(&["bootout", &self.service_target()])?;
        }
        #[cfg(target_os = "linux")]
        if self.service_file().exists() || self.service_running() {
            self.service_command(&[
                "disable",
                "--now",
                &format!("{}.service", self.service_label),
            ])?;
        }
        let deadline = Instant::now() + Duration::from_secs(10);
        while self.paths.base.exists() && ipc::lock(&self.paths).is_err() {
            if Instant::now() >= deadline {
                return Err(io::Error::other(
                    "daemon still running; stop it before uninstalling",
                ));
            }
            std::thread::sleep(Duration::from_millis(100));
        }
        Ok(())
    }

    pub fn doctor(&self, notify: bool) -> bool {
        let mut healthy = true;
        let mut check = |name: &str, result: Result<&str, String>| match result {
            Ok(detail) => println!("OK {name}: {detail}"),
            Err(fix) => {
                healthy = false;
                println!("FAIL {name}: {fix}");
            }
        };
        check(
            "user service",
            if read_regular(&self.service_file())
                .ok()
                .flatten()
                .is_some_and(|b| b == self.service_text().as_bytes())
                && self.service_running()
            {
                Ok("installed and loaded")
            } else {
                Err(
                    "run `ballast install` from the current binary in a logged-in user session"
                        .into(),
                )
            },
        );
        let reachable = self.reachable();
        check(
            "daemon",
            if reachable {
                Ok("reachable")
            } else {
                Err("run `ballast install`; inspect the user service log if it fails".into())
            },
        );
        check(
            "frozen work",
            if !reachable && recovery::needs_recovery(&self.paths) {
                Err("daemon unreachable with frozen work; run `ballast resume --all` now".into())
            } else {
                Ok("no stranded journal entries")
            },
        );
        for (path, agent) in self.config_files() {
            check(
                &format!("{agent} hooks"),
                self.hooks_current(&path, agent)
                    .map(|_| "present and pointing at this binary")
                    .map_err(|e| format!("{e}; run `ballast install` to repair")),
            );
        }
        check(
            "Codex trust",
            self.codex_trusted()
                .map(|_| "all Ballast hooks enabled and trusted")
                .map_err(|e| {
                    format!("{e}; open Codex, run /hooks, enable and approve the Ballast hooks")
                }),
        );
        match NativePlatform::new() {
            Ok(mut platform) => {
                check(
                    "pressure signals",
                    platform
                        .pressure()
                        .and_then(|p| {
                            if p.kernel_pressure_level.is_some()
                                || p.psi_full_avg10.is_some()
                                || (p.pageouts.is_some() && p.swapouts.is_some())
                            {
                                Ok("readable")
                            } else {
                                Err(io::Error::other("pressure inputs unavailable"))
                            }
                        })
                        .map_err(|e| format!("{e}; check OS pressure interfaces and permissions")),
                );
                let env_readable = platform
                    .list_processes(&Default::default(), &Default::default())
                    .ok()
                    .and_then(|ps| {
                        ps.into_iter()
                            .find(|p| p.identity.pid == std::process::id() as i32)
                    })
                    .is_some_and(|p| platform.read_environment(p.identity).is_some());
                check(
                    "process environment",
                    if env_readable {
                        Ok("readable for this user")
                    } else {
                        Err("cannot read own process environment; check OS process-access permissions".into())
                    },
                );
                if notify {
                    let enabled = crate::daemon::files::Config::load(&self.paths)
                        .map(|config| config.notifications);
                    check("notifications", match enabled.and_then(|enabled| {
                        platform.notifications = enabled;
                        platform.notify("Ballast", &crate::notifications::sample())
                    }) {
                        Ok(true) => Ok("submitted; confirm visible delivery on your desktop"),
                        Ok(false) => Err("disabled or unavailable; check notifications in config.toml and desktop permissions".into()),
                        Err(e) => Err(format!("{e}; check notification permissions and desktop session")),
                    });
                } else {
                    check(
                        "notifications",
                        if platform.capabilities().notifications {
                            Ok("helper available; run `ballast doctor --notify` to test delivery")
                        } else {
                            Err("helper unavailable; install notify-send in a desktop session, or use logs on a headless host".into())
                        },
                    );
                }
            }
            Err(e) => check(
                "platform",
                Err(format!("{e}; check OS process-access permissions")),
            ),
        }
        healthy
    }

    fn hooks_current(&self, path: &Path, agent: &str) -> io::Result<()> {
        let config = ConfigEdit::read(path.to_owned())?.value;
        if config.get("disableAllHooks").and_then(Value::as_bool) == Some(true) {
            return Err(io::Error::other(
                "disableAllHooks is enabled; turn it off in agent settings",
            ));
        }
        for (event, _) in EVENTS {
            let expected = self.hook_group(event, agent);
            let groups = config["hooks"][event]
                .as_array()
                .ok_or_else(|| io::Error::other("missing hook event"))?;
            if groups.iter().filter(|g| *g == &expected).count() != 1
                || groups
                    .iter()
                    .flat_map(|g| g["hooks"].as_array().unwrap())
                    .filter(|h| owned(h))
                    .count()
                    != 1
            {
                return Err(io::Error::other(
                    "missing, duplicate or outdated Ballast hook",
                ));
            }
        }
        Ok(())
    }

    fn codex_trusted(&self) -> io::Result<()> {
        let path = self.codex_dir.join("hooks.json");
        self.hooks_current(&path, "codex")?;
        let hooks = ConfigEdit::read(path.clone())?.value;
        let text = fs::read_to_string(self.codex_dir.join("config.toml")).unwrap_or_default();
        let config: toml::Value = toml::from_str(&text)
            .map_err(|_| io::Error::other("cannot parse Codex config.toml"))?;
        if config
            .get("features")
            .and_then(|f| f.get("hooks"))
            .and_then(|h| {
                h.as_bool()
                    .or_else(|| h.get("enabled").and_then(toml::Value::as_bool))
            })
            == Some(false)
        {
            return Err(io::Error::other("Codex features.hooks is disabled"));
        }
        for (event, key_event) in EVENTS {
            for (group_index, group) in hooks["hooks"][event].as_array().unwrap().iter().enumerate()
            {
                for (handler_index, hook) in group["hooks"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .enumerate()
                    .filter(|(_, h)| owned(h))
                {
                    let key = format!(
                        "{}:{key_event}:{group_index}:{handler_index}",
                        fs::canonicalize(&path)?.display()
                    );
                    let state = config
                        .get("hooks")
                        .and_then(|h| h.get("state"))
                        .and_then(|s| s.get(&key));
                    let trusted = state
                        .and_then(|s| s.get("trusted_hash"))
                        .and_then(toml::Value::as_str);
                    if state
                        .and_then(|s| s.get("enabled"))
                        .and_then(toml::Value::as_bool)
                        == Some(false)
                        || trusted != Some(codex_hash(key_event, group, hook).as_str())
                    {
                        return Err(io::Error::other(
                            "Ballast hook approval missing, changed or disabled",
                        ));
                    }
                }
            }
        }
        Ok(())
    }
}

fn env_path(name: &str, fallback: Option<PathBuf>) -> io::Result<PathBuf> {
    match std::env::var_os(name) {
        Some(value) if !value.is_empty() => Ok(PathBuf::from(value)),
        Some(_) => Err(io::Error::other(format!("{name} must not be empty"))),
        None => fallback.ok_or_else(|| io::Error::other(format!("{name} must be set"))),
    }
}
fn shell_quote(path: &Path) -> String {
    format!("'{}'", path.to_str().unwrap().replace('\'', "'\\''"))
}
#[cfg(target_os = "macos")]
fn xml(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}
#[cfg(target_os = "linux")]
fn systemd_quote(s: &str) -> String {
    format!(
        "\"{}\"",
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('%', "%%")
    )
}
fn service_command() -> Command {
    #[cfg(target_os = "macos")]
    let command = Command::new("launchctl");
    #[cfg(target_os = "linux")]
    let mut command = Command::new("systemctl");
    #[cfg(target_os = "linux")]
    command.arg("--user");
    command
}
fn owned(hook: &Value) -> bool {
    hook["type"] == "command"
        && hook["command"]
            .as_str()
            .is_some_and(|c| c.ends_with(MARKER))
}
fn remove_owned(config: &mut Value) {
    let Some(hooks) = config.get_mut("hooks").and_then(Value::as_object_mut) else {
        return;
    };
    hooks.retain(|_, groups| {
        let groups = groups.as_array_mut().unwrap();
        let had_owned = groups
            .iter()
            .any(|g| g["hooks"].as_array().unwrap().iter().any(owned));
        groups.retain_mut(|group| {
            let entries = group["hooks"].as_array_mut().unwrap();
            let had_owned = entries.iter().any(owned);
            entries.retain(|h| !owned(h));
            !had_owned || !entries.is_empty()
        });
        !had_owned || !groups.is_empty()
    });
}

// Codex hashes canonical JSON after TOML normalization: absent Option fields disappear,
// async defaults to false, and the persisted key uses the absolute source path and indices.
fn codex_hash(event: &str, group: &Value, hook: &Value) -> String {
    let mut handler = hook.clone();
    handler["async"] = json!(false);
    let mut identity = json!({"event_name": event, "hooks": [handler]});
    if let Some(matcher) = group.get("matcher") {
        identity["matcher"] = matcher.clone();
    }
    format!(
        "sha256:{:x}",
        Sha256::digest(serde_json::to_vec(&identity).unwrap())
    )
}

struct ConfigEdit {
    path: PathBuf,
    original: Option<Vec<u8>>,
    value: Value,
    changed: bool,
}
impl ConfigEdit {
    fn read(path: PathBuf) -> io::Result<Self> {
        let original = read_regular(&path)?;
        let value: Value = match &original {
            Some(bytes) => serde_json::from_slice(bytes).map_err(|_| {
                io::Error::other(format!(
                    "{}: malformed JSON; repair it before running install or uninstall",
                    path.display()
                ))
            })?,
            None => json!({}),
        };
        let valid = value.is_object()
            && value.get("hooks").is_none_or(|hooks| {
                hooks.as_object().is_some_and(|events| {
                    events.values().all(|groups| {
                        groups.as_array().is_some_and(|groups| {
                            groups.iter().all(|g| {
                                g.is_object()
                                    && g.get("matcher").is_none_or(Value::is_string)
                                    && g.get("hooks").and_then(Value::as_array).is_some_and(
                                        |hooks| {
                                            hooks.iter().all(|h| {
                                                h.get("type").is_some_and(Value::is_string)
                                                    && (h["type"] != "command"
                                                        || h.get("command")
                                                            .is_some_and(Value::is_string))
                                            })
                                        },
                                    )
                            })
                        })
                    })
                })
            });
        if !valid {
            return Err(io::Error::other(format!(
                "{}: malformed hook configuration; expected an object with hook-event arrays",
                path.display()
            )));
        }
        Ok(Self {
            path,
            original,
            value,
            changed: false,
        })
    }
    fn save(self) -> io::Result<()> {
        if !self.changed {
            return Ok(());
        }
        if read_regular(&self.path)? != self.original {
            return Err(io::Error::other(
                "hook config changed during installation; retry",
            ));
        }
        if let Some(original) = self.original {
            let stamp = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos();
            let backup = self.path.with_file_name(format!(
                "{}.ballast-backup-{stamp}",
                self.path.file_name().unwrap().to_string_lossy()
            ));
            let mut file = OpenOptions::new()
                .write(true)
                .create_new(true)
                .mode(0o600)
                .open(backup)?;
            file.write_all(&original)?;
            file.sync_all()?;
        }
        let mut bytes = serde_json::to_vec_pretty(&self.value)?;
        bytes.push(b'\n');
        atomic_write(&self.path, &bytes)
    }
}
fn read_regular(path: &Path) -> io::Result<Option<Vec<u8>>> {
    match fs::symlink_metadata(path) {
        Ok(meta) if !meta.is_file() => Err(io::Error::other(format!(
            "{} must be a regular file, not a symlink",
            path.display()
        ))),
        Ok(_) => fs::read(path).map(Some),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(e),
    }
}
fn atomic_write(path: &Path, bytes: &[u8]) -> io::Result<()> {
    let parent = path.parent().unwrap();
    fs::create_dir_all(parent)?;
    let temp = path.with_file_name(format!(
        ".ballast-{}-{}.tmp",
        std::process::id(),
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    let result = (|| {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&temp)?;
        file.write_all(bytes)?;
        file.sync_all()?;
        fs::rename(&temp, path)?;
        File::open(parent)?.sync_all()
    })();
    let _ = fs::remove_file(temp);
    result
}
fn remove_if_exists(path: &Path) -> io::Result<()> {
    match fs::remove_file(path) {
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(()),
        result => result,
    }
}

#[cfg(test)]
mod tests;
