#!/usr/bin/env python3
"""macOS spike for ticket 17, step 1.5: which unprivileged host-wide CPU and
disk I/O signals exist, and do they measure throughput or contention?

Passive reads only. No owned load is generated (no writes, no forced reads):
  - host_statistics(HOST_CPU_LOAD_INFO): cumulative CPU ticks across all
    cores since boot (user/system/idle/nice). A throughput signal (how much
    CPU time was consumed), not a queue-depth signal.
  - sysctl vm.loadavg: the closest unprivileged proxy to run-queue
    contention (a 1/5/15 min EWMA of runnable+running threads), but not a
    raw instantaneous run queue length -- no such counter was found exposed
    unprivileged on this OS build.
  - ioreg -c IOBlockStorageDriver Statistics: cumulative bytes/ops/time per
    physical device, unprivileged-readable. Throughput only; the
    "Latency Time" fields are present but read 0 on this driver, so per-op
    queueing latency is not directly available. Ticket 14's harness does
    NOT currently measure I/O latency (it measures sleep overshoot and page
    touch) -- ticket 17 step 3 is what proposes adding write+fsync and
    random-read latency probes, and this counter is not a substitute for
    those: it can only ever show ambient background activity here, never an
    approximated latency, since nothing here generates I/O.

Run: python3 spikes/darwin_host_signals_probe.py
"""
import ctypes
import re
import subprocess
import sys
import time

HOST_CPU_LOAD_INFO = 3
CPU_STATE_MAX = 4
CPU_STATE_NAMES = ("user", "system", "idle", "nice")

libc = ctypes.CDLL(None, use_errno=True)
libc.mach_host_self.restype = ctypes.c_uint


class host_cpu_load_info(ctypes.Structure):
    _fields_ = [("cpu_ticks", ctypes.c_uint * CPU_STATE_MAX)]


def read_cpu_ticks() -> list[int]:
    host = libc.mach_host_self()
    info = host_cpu_load_info()
    count = ctypes.c_uint(CPU_STATE_MAX)
    result = libc.host_statistics(host, HOST_CPU_LOAD_INFO, ctypes.byref(info), ctypes.byref(count))
    if result != 0:
        raise OSError(f"host_statistics failed: {result}")
    return list(info.cpu_ticks)


def read_loadavg() -> str:
    return subprocess.run(["sysctl", "-n", "vm.loadavg"], capture_output=True, text=True).stdout.strip()


def read_ncpu() -> str:
    return subprocess.run(["sysctl", "-n", "hw.ncpu"], capture_output=True, text=True).stdout.strip()


def read_block_storage_stats() -> list[str]:
    """One "Statistics" dict per matched IOKit node; physical devices are
    normally the entries with large cumulative counters."""
    out = subprocess.run(["ioreg", "-c", "IOBlockStorageDriver", "-r", "-l"], capture_output=True, text=True)
    if out.returncode != 0:
        raise OSError(f"ioreg failed: {out.stderr.strip()}")
    return re.findall(r'"Statistics" = \{([^}]*)\}', out.stdout)


def cpu_signal_demo() -> None:
    print("1. host CPU ticks (HOST_CPU_LOAD_INFO), a throughput signal:")
    before = read_cpu_ticks()
    time.sleep(2)
    after = read_cpu_ticks()
    delta = [b - a for a, b in zip(before, after)]
    total = sum(delta) or 1
    busy = delta[0] + delta[1] + delta[3]
    print(f"   ticks over 2s ({dict(zip(CPU_STATE_NAMES, delta))})")
    print(f"   busy fraction: {busy / total:.3f}  (ncpu={read_ncpu()})")
    print(f"2. vm.loadavg (closest unprivileged run-queue-contention proxy): {read_loadavg()}")
    print("   no raw instantaneous run-queue length counter was found exposed unprivileged")


def io_signal_demo() -> None:
    print("3. IOKit block storage Statistics, unprivileged read, passive only (no owned load):")
    stats = read_block_storage_stats()
    if len(stats) < 2:
        print("   fewer physical-driver Statistics nodes than expected; skipping delta demo")
        return
    before = stats[1]
    print(f"   before: {before}")
    time.sleep(3)
    after = read_block_storage_stats()[1]
    print(f"   after 3s idle (ambient system activity only, nothing generated by this script): {after}")
    print("   Latency Time fields are unpopulated on this driver; only cumulative Bytes/Operations/Total Time")
    print("   are readable. A real latency signal would need an owned write+fsync/read probe under an")
    print("   approved load -- exactly what ticket 17 step 3 proposes adding; not run here.")


if __name__ == "__main__":
    if sys.platform != "darwin":
        sys.exit("this spike only runs on macOS")
    cpu_signal_demo()
    io_signal_demo()
